// data/team.ts
export const teamMembers = [
  {
    name: "Harp",
    avatar: "Axolotl_1.png",
    role: "Owner",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: [
      "Owner of Creator Splash",
      "Game Concept Designer",
      "Project Manager",
    ],
  },
  {
    name: "Benji",
    avatar: "Axolotl_2.png",
    role: "Discord Admin",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: ["Discord Server Admin", "Discord Bot Administrator"],
  },
  {
    name: "Fridge",
    avatar: "Axolotl_3.png",
    role: "Discord Staff",
    country: "America",
    countryFlag: "US",
    responsibilities: ["Discord Moderator", "Backup Event Moderator"],
  },
  {
    name: "AgentOfLore",
    avatar: "Axolotl_4.png",
    role: "Discord Staff",
    country: "Australia",
    countryFlag: "AU",
    responsibilities: ["Discord Moderator", "Backup Event Moderator"],
  },
  {
    name: "Mizzen",
    avatar: "Axolotl_5.png",
    role: "Discord Staff",
    country: "Coming soon",
    countryFlag: "",
    responsibilities: ["Discord Moderator", "Backup Event Moderator"],
  },
  {
    name: "Dwarfed",
    avatar: "Axolotl_6.png",
    role: "Head Dev",
    country: "America",
    countryFlag: "US",
    responsibilities: ["Main Developer for Creator Splash", "UI/UX Specialist"],
  },
  {
    name: "Samus",
    avatar: "Axolotl_7.png",
    role: "Weapons Dev",
    country: "America",
    countryFlag: "US",
    responsibilities: ["Creates Kits we used for Multiverse"],
  },
  {
    name: "Boss Isaz",
    avatar: "Axolotl_8.png",
    role: "Texture Pack Artist",
    country: "France",
    countryFlag: "FR",
    responsibilities: ["Creator of Creator Splash Texture Pack"],
  },
  {
    name: "J48",
    avatar: "Axolotl_9.png",
    role: "Community Manager",
    country: "Syria",
    countryFlag: "SY",
    responsibilities: [
      "Head of Community Relations",
      "Head of Sponsorships",
      "Player Roster Help",
      "Social Media Helper",
    ],
  },
  {
    name: "AJX",
    avatar: "Axolotl_10.png",
    role: "Roster Manager",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: [
      "Team Management",
      "Roster Management",
      "Tester Recruitment",
      "Player Balancing",
    ],
  },
  {
    name: "Poke",
    avatar: "Axolotl_11.png",
    role: "Event Staff",
    country: "America",
    countryFlag: "US",
    responsibilities: ["Event Moderator"],
  },
  {
    name: "Jordan",
    avatar: "Axolotl_12.png",
    role: "Event Staff",
    country: "America",
    countryFlag: "US",
    responsibilities: ["Event Moderator", "Team Logo Designer", "Event Artist"],
  },
  {
    name: "Stardust",
    avatar: "Axolotl_13.png",
    role: "Event Staff",
    country: "Sweden",
    countryFlag: "SE",
    responsibilities: ["Event Moderator"],
  },
  {
    name: "Onyx",
    avatar: "Axolotl_14.png",
    role: "Event Staff",
    country: "Slovakia",
    countryFlag: "SK",
    responsibilities: ["Event Moderator"],
  },
  {
    name: "Ashlyn",
    avatar: "Axolotl_15.png",
    role: "Event Staff",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: ["Event Moderator"],
  },
  {
    name: "Cutie",
    avatar: "Axolotl_16.png",
    role: "Event Staff",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: ["Event Moderator"],
  },
  {
    name: "DatKid",
    avatar: "Axolotl_17.png",
    role: "Event Staff",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: ["Event Moderator"],
  },
  {
    name: "Layton",
    avatar: "Axolotl_18.png",
    role: "Event Staff",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: ["Event Moderator"],
  },
  // Audio Dept
  {
    name: "inod Studio",
    avatar: "Axolotl_19.png",
    role: "Music Producer",
    country: "Indonesia",
    countryFlag: "ID",
    responsibilities: ["Event Music Production"],
  },
  {
    name: "Paris Parasidis",
    avatar: "Axolotl_20.png",
    role: "Audio Engineer",
    country: "Greece",
    countryFlag: "GR",
    responsibilities: ["Mixxing and Mastering Vocals"],
  },
  {
    name: "Seapeekay",
    avatar: "Axolotl_21.png",
    role: "Voice Actor",
    country: "United Kingdom",
    countryFlag: "GB",
    responsibilities: ["Voice of Necromancer", "Voice of Monk"],
  },
  {
    name: "Talenthia R.",
    avatar: "Axolotl_22.png",
    role: "Voice Actor",
    country: "America",
    countryFlag: "US",
    responsibilities: ["Voice of Null"],
  },
];
